<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="robots" content="noindex">
    <title>SiSintegra - Recuperar senha</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='../css/bootstrap.min.css' >
    <link rel="stylesheet" href="../css/main.css">
    <script src="../js/jquery-1.10.2.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
</head>
<body>
<link rel="stylesheet" href="../css/font-awesome.min.css">
<link href="../css" rel="stylesheet" type="text/css">
<script src="../js/jquery.validate.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<div class="text-center" style="padding:50px 0">
	<div class="logo">Recuperar senha</div>
	<!-- Main Form -->
	<div class="login-form-1">
		<form id="forgot-password-form" class="text-left" novalidate="novalidate"  method="post">
			<div class="login-form-main-message"></div>
			<div class="main-login-form">
				<div class="login-group">
					<div class="form-group">
						<label for="fp_nome" class="sr-only">Nome do Usuário</label>
						<input type="text" class="form-control" id="fp_nome" name="fp_nome" placeholder="Nome">
					</div>
					<?php 
					if (isset($this->senha)){
						foreach($this->senha as $senha){ ?>
					<p>senha: <?php if (isset($usuarios->senha)){echo $usuarios->senha;} echo $senha["senha"];?></p>
					<?php }} ?>
				</div>
				<button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
			</div>
			<div class="etc-login-form">
				<p>Já possui uma conta? <a href="<?php echo $this->url(array('controller' => 'Index','action' => 'index')); ?>">Entre aqui</a></p>
				<p>Novo Usuário? <a href="<?php echo $this->url(array('controller' => 'Usuario','action' => 'novo')); ?>">Crie uma nova conta</a></p>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript" src="../js/main.js"></script>
</body></html>