<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="robots" content="noindex">

    <title>SiSintegra - Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='css/bootstrap.min.css' >
    <link rel="stylesheet" href="css/main.css">
    <script type='text/javascript' src='js/jquery-1.10.2.min.js'></script>
    <script type='text/javascript' src='js/bootstrap.min.js'></script>
    <script type='text/javascript'> 
	    var url = '<?php echo $this->baseUrl; ?>'; 
    </script>
</head>
<body>
<link rel="stylesheet" href="css/font-awesome.min.css">
<link href="./css" rel="stylesheet" type="text/css">
<script type='text/javascript' src='js/jquery.validate.min.js'></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<div class="text-center" style="padding:50px 0">
	<div class="logo">Login SiSintegra</div>
	<div class="login-form-1">
		<form id="login-form" class="text-left" novalidate="novalidate" method="post">
			<div class="login-form-main-message"></div>
			<div class="main-login-form">
				<div class="login-group">
					<div class="form-group">
						<label for="lg_nome" class="sr-only">Nome do Usuário</label>
						<input type="text" class="form-control" id="lg_nome" name="lg_nome" placeholder="Nome">
					</div>
					<div class="form-group">
						<label for="lg_senha" class="sr-only">Senha</label>
						<input type="password" class="form-control" id="lg_senha" name="lg_senha" placeholder="Senha">
					</div>
					<div class="form-group login-group-checkbox">
						<input type="checkbox" id="lg_remember" name="lg_remember">
						<label for="lg_remember">Lembrar</label>
					</div>
				</div>
				<button id="btnLogin" type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
				<div id='msjLogin'><label></label></div>
			</div>
			<div class="etc-login-form">
				<p>Esqueceu sua senha? <a href="<?php echo $this->url(array('controller' => 'Usuario','action' => 'senha')); ?>">Clique aqui</a></p>
				<p>Novo Usuário? <a href="<?php echo $this->url(array('controller' => 'Usuario', 'action' => 'novo')); ?>">Crie uma nova conta</a></p>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript" src="js/main.js"></script>
</body></html>