<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>SiSintegra</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
	<link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="css/main.css">
    <script src="js/jquery-1.10.2.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</head>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<script src="js/jquery.validate.min.js"></script>
<div class="text-center" style="padding:50px 0">
	<label>Bem vindo <?php echo $this->usuario; ?> </label><br>
	<div class="logo">Consultar novo CNPJ</div>
	<div class="login-form-1">
		<form id="se-form" class="text-left" novalidate="novalidate" method="post" action="<?php echo $this->url(array('controller'=>'raiz', 'action'=>'pesquisar'));?>">
			<div class="login-form-main-message"></div>
			<div class="main-login-form">
				<div class="login-group">
					<div class="form-group">
						<label for="se_cnpj" class="sr-only">CNPJ</label>
						<input type="text" class="form-control" id="se_cnpj" name="se_cnpj" placeholder="CNPJ">
					</div>
				</div>
				<button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
			</div>
			<div class="etc-login-form">
				<p>Efetuar <a href="<?php echo $this->url(array('controller'=>'autentifica', 'action'=>'logout-data'));?>">Logout</a></p>
			</div>
		</form>
	</div>
	<div class="widget stacked widget-table action-table">	
		<div class="widget-header">
			<i class="icon-th-list"></i>
			<h3>Lista de Consultas Realizadas</h3>
		</div>
		<div class="widget-content">
		<?php if(count($this->listaConsulta)){ ?>
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Id</th>
						<th>Usuário</th>
						<th>CNPJ</th>
						<th>Resultado</th>
						<th class="td-actions">Remover</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->listaConsulta as $consultas){ ?>
					<tr>
						<td><?php echo $consultas["id"]; ?></td>
						<td><?php echo $consultas["usuario"]; ?></td>
						<td><?php echo $consultas["cnpj"]; ?></td>
						<td><?php echo $consultas["resultado_json"]; ?></td>
						<td class="td-actions" style="text-align: center;">							
							<a href="<?php echo $this->url(array('controller'=>'raiz','action'=>'remove','id'=>$consultas["id"])) ?>" class="btn btn-small">
								<i class="btn-icon-only icon-remove"></i>	
							</a>
						</td>
					</tr>
					<?php } ?>
				</tbody>
				<tfoot>
					<td colspan="4">Total de consultas: <?= count($this->listaConsulta) ?></td>
				</tfoot>
			</table>
		<?php } ?>	
		</div>
	</div>
</div>
</body>
</html>
<script type="text/javascript" src="js/main.js"></script>